clinic_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# import myclinic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myclinic.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myclinic/urls.py
from django.urls import path

from myclinic import views

urlpatterns = [

    path('', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    # path('login-user', views.login_user, name='login-user'),
    path('register', views.register, name='register'),
    path('forgot-password', views.forgot_password, name='forgot-password'),
    path('lock-screen', views.lock_screen, name='lock-screen'),
    path('index', views.index, name='index'),
    path('my-profile/<slug>', views.my_profile, name='my-profile'),
    path('edit-profile/<slug>', views.edit_profile, name='edit-profile'),
    path('settings', views.settings, name='settings'),
    path('doctors', views.doctors, name='doctors'),
    path('add-doctor', views.add_doctor, name='add-doctor'),
    path('edit-doctors/<slug>', views.edit_doctors, name='edit-doctors'),
    path('delete-doctors/<slug>', views.delete_doctors, name='delete-doctors'),
    path('patients', views.patients, name='patients'),

    path('add-patient', views.add_patient, name='add-patient'),
    # path('edit-patient/<slug>', views.edit_patient, name='edit-patient'),
    path('edit-patient/<slug>', views.edit_patient, name='edit-patient'),
    path('delete-patient/<slug>', views.delete_patient, name='delete-patient'),
    path('appointments', views.appointments, name='appointments'),
    path('appointment-profile/<slug>', views.appointment_profile, name='appointment-profile'),
    path('add-appointment', views.add_appointment, name='add-appointment'),
    path('edit-appointment/<slug>', views.edit_appointment, name='edit-appointment'),
    path('edit-appointment/<slug>', views.edit_appointment, name='edit-appointment'),
    path('delete-appointment/<slug>', views.delete_appointment, name='delete-appointment'),
    path('schedule', views.schedule, name='schedule'),
    path('add-schedule', views.add_schedule, name='add-schedule'),
    path('edit-schedule/<id>', views.edit_schedule, name='edit-schedule'),
    path('delete-schedule/<id>', views.delete_schedule, name='delete-schedule'),
    path('department', views.department, name='department'),
    path('add-department', views.add_department, name='add-department'),
    path('edit-department/<id>', views.edit_department, name='edit-department'),
    path('delete-department/<id>', views.delete_department, name='delete-department'),
    path('employees', views.employee, name='employees'),
    path('add-employee/', views.add_employee, name='add-employee'),
    path('edit-employee/<slug>', views.edit_employee, name='edit-employee'),
    path('delete-employee/<slug>', views.delete_employee, name='delete-employee'),
    path('employee-profile/<slug>', views.employee_profile, name='employee-profile'),
    path('search', views.search_employee, name='search'),
]

myclinic/models.py
# from django import forms
from django import forms
from django.conf import settings
from django.core import serializers
from django.core.validators import MaxLengthValidator
from django.db import models
from django.db.models import TimeField
from django.utils.crypto import get_random_string
from datetime import datetime

# Create your models here.`
from django.utils.text import slugify
import random
import string
from .slug import unique_slugify


# '''
# random_string_generator is located here:
# http://joincfe.com/blog/random-string-generator-in-python/
# '''


# from clinic_management_system.utils import random_string_generator
# from utils import random_string_generator


# def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
#     # print(''.join(random.choice(chars) for _ in range(size)))
#     return ''.join(random.choice(chars) for _ in range(size))

# def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
#     return ''.join(random.choice(chars) for _ in range(size))


# def unique_slug_generator(instance, new_slug=None):
#     """
#     This is for a Django project and it assumes your instance
#     has a model with a slug field and a title character (char) field.
#     """
#
#     if new_slug is not None:
#         slug = new_slug
#     else:
#         slug = slugify(instance.fname)
#
#     Klass = instance.__class__
#     qs_exists = Klass.objects.filter(slug=slug).exists()
#     if qs_exists:
#         new_slug = "{slug}-{randstr}".format(
#             slug=slug,
#             randstr=random_string_generator(size=4)
#             # randstr=random_string_generator(7).upper()
#         )
#         # print(unique_slug_generator(instance, new_slug=new_slug))
#         return unique_slug_generator(instance, new_slug=new_slug)
#     return slug


def generate_id_length():
    code_length = 7
    return get_random_string(code_length).upper()


class Country(models.Model):
    COUNTRY_CHOICES = (
        ('United States', 'United States'),
        ('United Kingdom', 'United Kingdom'),
        ('Australia', 'Australia'),
        ('Nepal', 'Nepal'),
        ('China', 'China'),
        ('Poland', 'Poland'),
        ('Japan', 'Japan'),
    )
    country = models.CharField(max_length=25, choices=COUNTRY_CHOICES, verbose_name="Country")

    class Meta:
        verbose_name_plural = "Country"

    def __str__(self):
        return self.country


class State(models.Model):
    STATE_CHOICES = (
        ('Province 1', 'Province 1'),
        ('Madhesh Province', 'Madhesh Province'),
        ('Bagmati Province', 'Bagmati Province'),
        ('Gandaki Province', 'Gandaki Province'),
        ('Lumbini Province', 'Lumbini Province'),
        ('Karnali Province', 'Karnali Province'),
        ('Sudurpashim Province', 'Sudurpashim Province'),
    )
    state = models.CharField(max_length=25, choices=STATE_CHOICES)

    class Meta:
        verbose_name_plural = "State"

    def __str__(self):
        return self.state


class Department(models.Model):
    DEPARTMENT_CHOICES = (
        ('Dentists', 'Dentists'),
        ('Neurology', 'Neurology'),
        ('Opthamology', 'Opthamology'),
        ('Orthopedics', 'Orthopedics'),
        ('Cancer Department', 'Cancer Department'),
        ('ENT Department', 'ENT Department'),
    )
    # DEPARTMENT_CHOICES = (
    #     ('DEN', 'Dentists'),
    #     ('NEU', 'Neurology'),
    #     ('OPT', 'Opthamology'),
    #     ('ORT', 'Orthopedics'),
    #     ('CAN', 'Cancer Department'),
    #     ('ENT', 'ENT Department'),
    # )
    department = models.CharField(max_length=93, choices=DEPARTMENT_CHOICES)
    description = models.TextField()

    STATE_CHOICES = (
        ('A', 'Active'),
        ('B', 'Inactive'),
    )
    status = models.CharField(max_length=1, choices=STATE_CHOICES)

    def is_activated(self):
        if self.status == 'A':
            return True
        return False

    is_activated.boolean = True
    is_activated.short_description = "Status"

    def __str__(self):
        return self.department


class Departmentzz(models.Model):
    department = models.CharField(max_length=93)
    description = models.TextField()

    STATE_CHOICES = (
        ('A', 'Active'),
        ('B', 'Inactive'),
    )
    status = models.CharField(max_length=1, choices=STATE_CHOICES)

    def is_activated(self):
        if self.status == 'A':
            return True
        return False

    is_activated.boolean = True
    is_activated.short_description = "Status"

    def __str__(self):
        return self.department


class Days(models.Model):
    DAYS_CHOICES = (
        ('Sunday', 'Sunday'),
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
    )
    # days = models.CharField(max_length=10, choices=DAYS_CHOICES)
    days = models.CharField(max_length=10, choices=DAYS_CHOICES)

    class Meta:
        verbose_name_plural = 'Days'

    def __str__(self):
        return self.days

    # def dayz(self):
    #     return ("%s" % (self.days   ))
    #
    # dayz.short_description = 'Choose days'


class DocProfile(models.Model):
    code_length = 7
    code = models.CharField(max_length=code_length, editable=False, default=generate_id_length, unique=True, verbose_name='Doctor ID')
    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, **kwargs):
        slug = '%s' % self.fname
        unique_slugify(self, slug)
        super(DocProfile, self).save()

    @property
    def fullname(self):
        return f"{self.fname} {self.lname}"

    username = models.CharField(max_length=255)

    # country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True, related_name='countryz')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True, related_name='countryz')
    city = models.CharField(max_length=255)

    # state = models.ForeignKey(State, on_delete=models.CASCADE, blank=True, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, blank=True, null=True)
    postal_code = models.IntegerField()

    medical_area = models.TextField()
    phone = models.IntegerField()
    email = models.EmailField(max_length=255)
    birthday = models.DateField(auto_now=False)
    address = models.CharField(max_length=255)
    image = models.ImageField(upload_to='img')
    edu_info = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def image_tag(self):
    #     return mark_safe('<img src="/img/%s" width="150" height="150" />' % self.image.url)
    #
    # image_tag.short_description = 'Image'
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    STATE_CHOICES = (
        ('A', 'Active'),
        ('B', 'Inactive'),
    )
    status = models.CharField(max_length=1, choices=STATE_CHOICES)

    def is_activated(self):
        if self.status == 'A':
            return True
        return False

    is_activated.boolean = True
    is_activated.short_description = "Status"

    def __str__(self):
        return self.fname + ' ' + self.lname

    class Meta:
        verbose_name = 'Doctor'

# def generate_id_length():
#     code_length = 7
#     return get_random_string(code_length).upper()


class Patient(models.Model):
    code_length = 7
    code = models.CharField(max_length=code_length, editable=False, default=generate_id_length, unique=True, verbose_name='Patient ID')
    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length=255)
    # name = fname + lname
    uname = models.CharField(max_length=255, verbose_name='username')
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, **kwargs):
        slug = '%s' % (self.uname)
        unique_slugify(self, slug)
        super(Patient, self).save()

    disease = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # password = models.CharField(max_length=20, widget=forms.PasswordInput)
    # c_password = models.CharField(max_length=20, widget=forms.PasswordInput)

    email = models.EmailField(max_length=255)
    birthday = models.DateField(auto_now=False)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    address = models.CharField(max_length=255)

    # country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    # state = models.ForeignKey(State, on_delete=models.CASCADE, blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, blank=True, null=True)

    city = models.CharField(max_length=255)

    postal_code = models.IntegerField()
    phone = models.IntegerField()
    image = models.ImageField(upload_to='img/patients', null=True)

    STATE_CHOICES = (
        ('A', 'Active'),
        ('B', 'Inactive'),
    )
    status = models.CharField(max_length=1, choices=STATE_CHOICES)

    def is_activated(self):
        if self.status == 'A':
            return True
        return False

    is_activated.boolean = True
    is_activated.short_description = "Status"

    @property
    def fullname(self):
        return f"{self.fname} {self.lname}"

    def __str__(self):
        return self.fullname


# def generate_id_length():
#     code_length = 7
#     return get_random_string(code_length).upper()


class Appointment(models.Model):
    code_length = 7

templates/pages/appointments/add-appointment.html
{% extends 'master/master.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
    <script src="{% static 'assets/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>


    <script>
        $(function () {
            $('#datetimepicker3').datetimepicker({
                format: 'LT'

            });
        });
    </script>

    <style>
        .asteriskField {
            display: none;
        }
    </style>

    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h4 class="page-title">Add Appointment</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <form action="{% url 'add-appointment' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.fname | as_crispy_field }}
                                </div>
                            </div>
                             <div class="col-md-6" hidden>
                                <div class="form-group">
                                    {{ apt_form.slug | as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.lname |as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.age | as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.address |as_crispy_field }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                             <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.country |as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.department |as_crispy_field }}
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.doctor |as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="cal-icon">
                                        {{ apt_form.date |as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="time-icon">
                                        {{ apt_form.time | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.email |as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.phone |as_crispy_field }}
                                </div>
                            </div>
                        </div>

                        <div class="form-group message">
                            {{ apt_form.message |as_crispy_field }}
                        </div>
                        <div class="form-group">
                            {{ apt_form.status |as_crispy_field }}
                        </div>
                        <div class="m-t-20 text-center">
                            <button class="btn btn-primary submit-btn">Create Appointment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });

        $(function () {
            $('.time-input').datetimepicker({
                format: 'HH:mm:ss',
                {#format: 'LT ',#}

            });
        });
        $(function () {
            $('.ranjan').addClass('form-check-inline')
        });

    </script>

{% endblock %}

templates/pages/appointments/appointments.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
    <script src="{% static 'assets/js/messages.js' %}"></script>

    <script src="{% static 'assets/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static '/static/assets/js/app.js' %}"></script>
    <style>
        .form-control.form-control-sm {
            padding: 0.1rem 0.91rem;
        }

        .table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
            background-color: #8ae6ee;
        }
    </style>
    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success" role="alert">{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="col-sm-4 col-3">
                    <h4 class="page-title">Appointments</h4>
                </div>
                <div class="col-sm-8 col-9 text-right m-b-20">
                    <a href="{% url 'add-appointment' %}" class="btn btn btn-primary btn-rounded float-right"><i
                            class="fa fa-plus"></i> Add Appointment</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-border table-striped custom-table datatable mb-0 table-hover">
                            <thead>
                            <tr>
                                <th>Appointment ID</th>
                                <th>Patient Name</th>
                                <th>Age</th>
                                <th>Address</th>
                                <th>Doctor Name</th>
                                <th>Department</th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                                <th>Status</th>
                                <th class="text-right">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for appointment in app_obj %}
                                <tr>
                                    <td>{{ appointment.code }}</td>
                                    <td> {{ appointment.fullname }}</td>
                                    <td>{{ appointment.age }}</td>
                                    <td>{{ appointment.address |title }}</td>
                                    <td><img width="40" height="40" src="{{ appointment.doctor.image.url }}"
                                             class="rounded-circle m-r-5" alt="">
                                        {{ appointment.doctor }}</td>
                                    <td>{{ appointment.department.get_department_display }}</td>
                                    <td>{{ appointment.date }}</td>
                                    <td>{{ appointment.time }}</td>
                                    <td><span class="custom-badge status-{% if appointment.is_activated == True %}green {% else %}red {% endif %}">{{ appointment.get_status_display }}</span></td>
                                    <td class="text-right">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                               aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="{% url 'edit-appointment' appointment.slug %}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                                <a class="dropdown-item"
                                                   href="{% url 'delete-appointment' appointment.slug %}" data-toggle="modal" data-target="#delete_appointment{{ appointment.slug }}"><i
                                                        class="fa fa-trash-o m-r-5"></i>
                                                    Delete</a>
                                            </div>
                                        </div>
                                        <form action="{% url 'delete-appointment' appointment.slug %}" method="post">
                                            {% csrf_token %}
                                            <div id="delete_appointment{{ appointment.slug }}" class="modal fade delete-modal" role="dialog">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-body text-center">
                                                            <img src="{% static 'assets/img/sent.png' %}" alt="" width="50" height="46">
                                                            <h3>Are you sure want to delete this Appointment?</h3>
                                                            <div class="m-t-20"><a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
                                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/appointments/edit-appointment.html
{% extends 'master/master.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
    <style>
        .asteriskField {
            display: none;
        }
    </style>
    <script src="{% static 'assets/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>

    <div class="page-wrapper">
        <div class="content">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h4 class="page-title">Edit Appointment</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <form action="{% url 'edit-appointment' appointment_obj.slug %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Appointment ID</label>
                                    <input class="form-control" type="text" value="{{ appointment_obj.code }}"
                                           readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.fname | as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.lname |as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.age | as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.address |as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.country |as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.department |as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ apt_form.doctor |as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="cal-icon">
                                        {{ apt_form.date |as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="time-icon">
                                        {{ apt_form.time | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.email |as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ apt_form.phone |as_crispy_field }}
                                </div>
                            </div>
                        </div>

                        <div class="form-group message">
                            {{ apt_form.message |as_crispy_field }}
                        </div>
                        <div class="form-group">
                            {{ apt_form.status |as_crispy_field }}
                        </div>
                        <div class="m-t-20 text-center">
                            <button class="btn btn-primary submit-btn">Update Appointment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });

        $(function () {
            $('.time-input').datetimepicker({
                format: 'HH:mm:ss',
                {#format: 'LT ',#}

            });
        });


    </script>

{% endblock %}